#!/usr/bin/env bash
set -euo pipefail
shopt -s extglob

# create a temporary directory to clone the repository
# this will be used to check out the repository and execute
# the build process
tmpdir=$(mktemp -d)
cursor_path="$tmpdir"/cursors
echo -en "Building in temporary directory: $tmpdir\n"

# Sparsely check out to the repository
# specifically to the src/ directory where
# vector (svg) versions of the Catppuccin cursors
# are located
git clone --depth=1 --filter=blob:none --sparse https://github.com/catppuccin/cursors "$cursor_path"
cd "$cursor_path" || exit
git sparse-checkout init --cone
git sparse-checkout set src/
echo -en "Cloned repository at $tmpdir/cursors\n"

SVGDIR="${1-"$cursor_path"}" # should generally be cursors/src but user may choose to cd themselves
NAMED="${2:-hyprcursor}"
ANIMONE="${3:-"wait"}"
ANIMTWO="${4:-"progress"}"

if [ ! -d "$SVGDIR" ]; then
	echo "Error: Directory '$SVGDIR' does not exist."
	exit 1
fi

if [ -f "$SVGDIR/manifest.hl" ]; then
	echo "Error: $SVGDIR already has a manifest.hl file."
	exit 1
fi

# prepare directory, remove any extraneous files

echo -en "Step 1: Preparing directory\n"
cd "$SVGDIR" || exit
mkdir "$ANIMONE" "$ANIMTWO" || exit # if mkdir fails for any reason, exit early
mv -v "$ANIMONE"-* "$ANIMONE"
mv -v "$ANIMTWO"-* "$ANIMTWO"

# create a containing folder with name of icon
echo -en "Step 2: Creating folders\n"
for file in "${NAMED}"/*.svg; do
	file_contents="
    resize_algorithm = bilinear
    define_size = 64, $file
    "
	direct="${file%.svg}"
	mkdir -- "$direct"
	mv -- "$file" "$direct"
	echo "$file_contents" >"$direct"/meta.hl
done

function process_meta() {
	local ANIM="$1"
	local output=""
	for i in {1..12}; do
		output+="define_size = 64, $ANIM-$(printf "%02d" "$i").svg,500\n"
	done

	echo -e "resize_algorithm = bilinear\n$output" >"$ANIM"/meta.hl
}

echo -en "Step 3: Processing meta files\n"
process_meta "$ANIMONE"
process_meta "$ANIMTWO"

mv !(cursors) ./cursors
rm cursors/index.theme

# index.theme gen
echo "[Icon Theme]
Name=$NAMED
Comment=generated by hyprman
" >>index.theme

echo "name = $NAMED
description = let there be ants
version = 0.1
cursors_directory = cursors
" >>manifest.hl

hyprcursor-util --create ./.
